import Anthropic from '@anthropic-ai/sdk'

// Serverless runtime on Vercel Pro: up to 300s total duration.
// Edge has a hard 25s first-byte limit on all plans — Serverless avoids this.
export const maxDuration = 300

const SYSTEM_PROMPT = `You are an aviation intelligence analyst for Aviate Pro, a professional flight operations platform. Your role is to research and compile comprehensive, accurate aviation reports for aviation professionals.

When generating reports:
1. Search for current and relevant aviation information including: incidents, accidents, airspace closures, NOTAMs, weather advisories, regulatory changes, fleet news, airline operations, and industry developments worldwide
2. Present findings in a structured, professional format suitable for pilots, dispatchers, and aviation operations staff
3. Include specific details: dates, times (UTC where applicable), locations, ICAO codes, aircraft types, flight numbers, and regulatory references where relevant
4. Note the recency of information and flag anything time-sensitive

Use this report structure:
## [Descriptive Report Title]
**Generated:** [current date/time UTC] | **Type:** Aviation Intelligence Report

### Executive Summary
[2-3 sentence overview of key findings]

### Key Findings
- [Bulleted key points]

### Detailed Analysis
[Comprehensive section-by-section analysis with subsections as needed]

### Safety & Regulatory Implications
[Relevant safety and regulatory aspects]

### Recommendations
[Actionable items for aviation operations staff, if applicable]

---
*Report generated by Aviate Pro AI Intelligence System | Data sourced from web search at time of generation*`

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json()

    if (!prompt?.trim()) {
      return Response.json({ error: 'Prompt is required' }, { status: 400 })
    }

    const apiKey = process.env.ANTHROPIC_API_KEY
    if (!apiKey) {
      return Response.json(
        { error: 'ANTHROPIC_API_KEY is not configured.' },
        { status: 500 }
      )
    }

    const client = new Anthropic({
      apiKey,
      defaultHeaders: { 'anthropic-beta': 'web-search-2025-03-05' },
    })

    const encoder = new TextEncoder()

    const readable = new ReadableStream({
      async start(controller) {
        const send = (data: object) =>
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`))

        try {
          // Flush an immediate keep-alive so Vercel registers an initial response
          // before the Anthropic API call begins (avoids gateway timeout on cold starts).
          send({ ping: true })

          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const tools: any[] = [{ type: 'web_search_20250305', name: 'web_search' }]

          // True streaming: tokens are forwarded as Claude generates them.
          // web_search_20250305 is executed server-side by Anthropic — no agentic
          // loop needed. The stream handles tool events transparently.
          const stream = client.messages.stream({
            model: 'claude-haiku-4-5-20251001',
            max_tokens: 4096,
            system: SYSTEM_PROMPT,
            tools,
            messages: [{ role: 'user', content: prompt }],
          })

          for await (const event of stream) {
            if (
              event.type === 'content_block_start' &&
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              (event.content_block as any)?.type === 'tool_use'
            ) {
              // Send a keep-alive ping while Claude is executing the web search.
              // This prevents Vercel from closing the idle connection.
              send({ ping: true })
            } else if (
              event.type === 'content_block_delta' &&
              event.delta.type === 'text_delta'
            ) {
              send({ text: event.delta.text })
            }
          }

          controller.enqueue(encoder.encode('data: [DONE]\n\n'))
          controller.close()
        } catch (err) {
          console.error('[aviation-report] stream error:', err)
          const msg = err instanceof Error ? err.message : 'Report generation failed'
          send({ error: msg })
          controller.close()
        }
      },
    })

    return new Response(readable, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
    })
  } catch (err) {
    console.error('[aviation-report] request error:', err)
    const msg = err instanceof Error ? err.message : 'Server error'
    return Response.json({ error: msg }, { status: 500 })
  }
}
